### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by b-cannon** [GoogleCloudPlatform/getting-started-python#40]
Going through the tutorial and everything went fine until section 4-auth.  I deployed it, and when I try to log in, I get '502 Bad Gateway'.  I didn't change anything.  One thing in the tutorial I did have to change in the settings for authorized redirect uri, it wasn't working with  https://....appspot.com, but did work when I changed it to http://.....appspot.com

**Comment by tutnes** [comment]
I am having auth issues as well.

**Comment by waprin** [comment]
Reproduced the 502, also had another error before that on json decodes for Python3. Will try to get this fixed asap, thanks for report.

**Comment by tutnes** [comment]
Seems like the JSON thing (str bytes issue) is fixed but now i get a "gcloud.exceptions.BadRequest: 400 The Cloud Datastore API is not enabled for the project"

**Comment by waprin** [comment]
Sorry for the delay in fixing this, ran into a bunch of quirky issues, still hoping to get it fixed very soon.

**Comment by b-cannon** [comment]
I had the json decodes thing too with python 3, but I believe I switched to python 2 which fixed that problem.  I think there's something with python 3 not decoding json the same way as 2.

**Comment by waprin** [comment]
So we have identified the root cause of this issue. Cookies have a maximum size of 4kb and the oauth2 flow stores some data that is close to that in size which is breaking the nginx proxy. There is also a bug in the memcache proxy that prevents storing more then 4kb. We are rolling out a fix this week that will use less session space in the oauth2 proxy to workaround this issue, and long-term  there will be a fix to the memcache issue so we can migrate to memcache for session data.

**Comment by waprin** [comment]
Ok, we released a new oauth2client that uses less session data and this repo has been updated so this issue should no longer occur if you follow our guide. Make sure you clear any existing cookies when you test this.

However keep in mind that the 4kb cookie session limit exists so be careful about how much data you put into your session, prefer to use the database option for bigger data. We will switch to memcache sessions ASAP to alleviate the issue at which point you can put 1MB into the session, however we are still waiting for a fix of the memcache proxy to do so.
