### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by beshaya** [GoogleCloudPlatform/getting-started-python#92]
I set this up on my local machine with CloudSQL and it works great, but when I pushed to AppEngine with gcloud app deploy and go to the resulting webpage, I get:

(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

Any idea what's up?

**Comment by jonparrott** [comment]
Hi, a few questions:

1. Are you using Cloud SQL 2nd Generation?
2. Did you uncomment [this line](https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/2-structured-data/app.yaml#L33) in app.yaml?
3. Can you double check [these settings](https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/2-structured-data/config.py#L40)?

**Comment by beshaya** [comment]
1. Yes
2. Yes
3. Yes - as noted, this works locally.

On Fri, Sep 30, 2016 at 9:58 AM, Jon Wayne Parrott <notifications@github.com

**Comment by jonparrott** [comment]
Thanks, I'll try to reproduce.

**Comment by jonparrott** [comment]
Hrm, I wasn't able to reproduce. Can you paste in your config.py with your project id and password elided?

**Comment by beshaya** [comment]
config: http://pastebin.com/YVaxKeUg
app.yaml: http://pastebin.com/t1MjCD6e

**Comment by jonparrott** [comment]
@beshaya Hmmm, all of your configuration looks correct.

Can you check and make sure the Cloud SQL Admin API is enabled in the cloud console?

**Comment by fermaf** [comment]
I have the same problem than @beshaya!
works fine locally but when deply to GEA, Can't connect to MySQL server on 'localhost' raices.

(Cloud SQL is enabled)

**Comment by jonparrott** [comment]
This may just be an issue with the environment variable. I'm investigating.

**Comment by jonparrott** [comment]
Hmm - the environment variable seems correct. I'm not sure why this is occurring and I can't seem to reproduce. Could you try printing the `SQLALCHEMY_DATABASE_URI` at the end of config.py and seeing what it's pointing to in your logs?

**Comment by beshaya** [comment]
Hi John,

I've given up on CloudSQL and switched to Firebase. It's a better fit for
my application.

One thought - does it matter whether I'm using a standard or flexible app
engine instance?

**Comment by jonparrott** [comment]
@beshaya this application is intended for flexible. You can use Cloud SQL from both standard and flexible, but the configuration is slightly different between the two.

For Firebase, it shouldn't matter.

**Comment by ajpharrington** [comment]
Did anyone ever find a solution to this problem? I am facing it as well.

**Comment by larsblumberg** [comment]
I described a potential solution (enabling Cloud SQL Admin API) here: https://github.com/GoogleCloudPlatform/getting-started-python/issues/129#issuecomment-332803546

**Comment by bwindsor22** [comment]
@larsblumberg 's solution worked for me, enabling the administration api.

Can we also add this as a step to the tutorial here? https://cloud.google.com/python/getting-started/tutorial-app  

Ideal would be to pass this solution in the error text, as app logs aren't visible by default from command line. Not sure how hard that is.

**Comment by jonparrott** [comment]
@bwindsor22 the "Enable the APIs" button already ensures that the SQL Admin API is enabled.

**Comment by bwindsor22** [comment]
@jonparott, ah, I see

**Comment by kiptoomm** [comment]
> this application is intended for flexible. You can use Cloud SQL from both standard and flexible, but the configuration is slightly different between the two.

@theacodes would you please elaborate on how configurations between the two differ?

*context* (maybe this part should be a separate question or stackoverflow post, so you can ignore if it's not relevant): I'm trying to work around this problem, none of the solutions here or in the linked issues have worked for me so far. I created a project for the Standard Environment following https://cloud.google.com/appengine/docs/standard/python/cloud-sql/using-cloud-sql-mysql#setting-up, but would like to use pymysql instead of MySQLdb because it has been a pain trying to install the latter on my system (macOS, using virtualenv). I would like to know if it is possible to use pymysql in a Standard Environment, and if so, how to set up the configs?

**Comment by theacodes** [comment]
@andrewsg should be able to help

**Comment by kiptoomm** [comment]
I'm not sure if it's true at all but so far from my experience and that of OP in this [SO post](https://stackoverflow.com/a/41082373/1145905) it seems PyMySQL is not supported in the standard environment. @andrewsg can confirm? Or know an alternative? Still facing [headaches installing MySQLdb](https://stackoverflow.com/questions/38549431/mysql-python-install-mac) on mac+virtualenv

**Comment by andrewsg** [comment]
I can confirm that pymysql is not supported in the python27 runtime. However, for most use cases, it's possible to use pymysql locally and mysqldb in production by using a `try:` / `except ImportError:` to import one or the other conditionally. As they share the same interface, you can use `import from` to make the two different libraries share the same name for ease of use in your code.

Django is a special case since the database driver is configured by the framework and not invoked directly. If you are using Django, you can put this at the top of your settings.py file:

    try:
        import pymysql
        pymysql.install_as_MySQLdb()
    except ImportError:
        pass

**Comment by kiptoomm** [comment]
Good to know, @andrewsg. I finally managed to install MySQLdb locally after fighting for a few days with virtualenv. Issue was related to the `DistutilsOptionError` discussed further in this [Stack Overflow post](https://stackoverflow.com/a/44728772/1145905)

**Comment by onavsaber** [comment]
I have the same issue, following the steps [here](https://cloud.google.com/python/django/appengine). The app runs fine locally, but gives the same error as mentioned when deployed. Are there any solutions?
